-- File: src/main/resources/db/migration/V1__create_tables.sql
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255),
    tipo_usuario VARCHAR(50)
);

CREATE TABLE filme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255)
);

CREATE TABLE avaliacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota INTEGER NOT NULL CHECK (nota BETWEEN 0 AND 5),
    comentario TEXT,
    data_avaliacao DATE,
    usuario_id BIGINT NOT NULL,
    filme_id BIGINT NOT NULL,
    CONSTRAINT fk_avaliacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_avaliacao_filme FOREIGN KEY (filme_id) REFERENCES filme(id)
);

CREATE TABLE favorito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_favorito DATE,
    usuario_id BIGINT NOT NULL,
    filme_id BIGINT NOT NULL,
    CONSTRAINT fk_favorito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_favorito_filme FOREIGN KEY (filme_id) REFERENCES filme(id)
);
